# This is a basic workflow that is manually triggered

name: Build ImmortalWrt 23.05.3 with Custom Packages

on:
  workflow_dispatch:
    inputs:
      target_device:
        description: 'Target device (e.g., x86_64, rpi-4)'
        required: true
        default: 'x86_64'

env:
  IMMORTALWRT_VERSION: '23.05.3'
  REPO_URL: 'https://github.com/immortalwrt/immortalwrt'
  REPO_BRANCH: 'openwrt-23.05'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码（包括你的 .config 文件）
      - name: Checkout
        uses: actions/checkout@v3

      # 设置构建环境
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache curl file g++ gawk \
            git libncurses5-dev libssl-dev python3 unzip zlib1g-dev

      # 下载 ImmortalWrt 源码
      - name: Clone ImmortalWrt Source
        run: |
          git clone --depth 1 -b ${{ env.REPO_BRANCH }} ${{ env.REPO_URL }} immortalwrt
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 应用预设 .config 文件并添加额外软件包
      - name: Apply custom configuration
        run: |
          cd immortalwrt
          # 将仓库中的 .config 复制到源码目录
          cp ../.config .config

          # 添加所需的软件包（确保 feeds 中可用）
          git clone https://github.com/vernesong/OpenClash.git package/openclash
          git clone https://github.com/xiaorouji/openwrt-passwall.git package/passwall
          git clone https://github.com/immortalwrt/homeproxy.git package/homeproxy
          git clone https://github.com/lisaac/luci-app-dockerman.git package/dockerman
          git clone https://github.com/kenzok8/luci-theme-argon.git package/luci-theme-argon

          # 更新 feeds 并安装
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # 确保配置生效
          make defconfig

      # 编译固件
      - name: Build Firmware
        run: |
          cd immortalwrt
          make -j$(nproc) V=s

      # 上传固件（使用 v4 版本）
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware-${{ github.event.inputs.target_device }}
          path: immortalwrt/bin/targets/*/*/immortalwrt-*.bin
