name: Build OpenWrt Snapshot for x86_64 with I226 Support, HomeProxy, OpenClash, and Docker

on:
  workflow_dispatch:
    inputs:
      make_threads:
        description: 'Threads for compilation (1-4, smaller is more stable)'
        required: true
        default: '2'

env:
  REPO_URL: 'https://github.com/openwrt/openwrt'
  REPO_BRANCH: 'main'  # Snapshot branch
  ROOTFS_PARTSIZE: '2048'
  TARGET_DEVICE: 'x86_64'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache
          sudo apt-get clean
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache curl file g++ gawk \
            git libncurses5-dev libssl-dev python3 unzip zlib1g-dev \
            subversion libxml-parser-perl default-jre-headless

      - name: Clone OpenWrt Source
        run: |
          git clone --depth 1 -b ${{ env.REPO_BRANCH }} ${{ env.REPO_URL }} openwrt
          cd openwrt
          echo "CONFIG_DOWNLOAD_FOLDER=\"$(pwd)/dl\"" > .config
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure OpenWrt
        run: |
          cd openwrt
          
          # Clone OpenClash
          git clone https://github.com/vernesong/OpenClash.git package/openclash
          if [ $? -ne 0 ]; then echo "Failed to clone OpenClash"; exit 1; fi
          
          # Clone HomeProxy
          git clone https://github.com/immortalwrt/homeproxy.git package/homeproxy
          if [ $? -ne 0 ]; then echo "Failed to clone HomeProxy"; exit 1; fi
          
          # Clone DockerMan (luci-app-dockerman)
          git clone https://github.com/lisaac/luci-app-dockerman.git package/luci-app-dockerman
          if [ $? -ne 0 ]; then echo "Failed to clone DockerMan"; exit 1; fi

          # Update feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # Generate configuration for x86_64
          cat << EOF > .config
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-opkg=y
          
          # Core packages
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-homeproxy=y
          CONFIG_PACKAGE_luci-app-dockerman=y
          CONFIG_PACKAGE_docker=y
          CONFIG_PACKAGE_dockerd=y
          
          # Network drivers (including Intel I226)
          CONFIG_PACKAGE_kmod-igc=y    # Intel I226 2.5Gbps support
          CONFIG_PACKAGE_kmod-r8168=y  # 2.5Gbps Realtek RTL8125
          CONFIG_PACKAGE_kmod-r8169=y  # 1Gbps Realtek
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
          
          # Language support
          CONFIG_LUCI_LANG_zh_Hans=y   # Chinese (Simplified)
          
          # System configuration
          CONFIG_TARGET_ROOTFS_PARTSIZE=${{ env.ROOTFS_PARTSIZE }}
          CONFIG_TARGET_ROOTFS_EXT4FS=y
          CONFIG_TARGET_ROOTFS_SQUASHFS=y
          CONFIG_CCACHE=y
          
          # Lean configuration for stability
          CONFIG_KERNEL_KALLSYMS=n
          CONFIG_KERNEL_DEBUG_INFO=n
          CONFIG_KERNEL_DEBUG_KERNEL=n
          CONFIG_KERNEL_SWAP=n
          EOF
          
          make defconfig

      - name: Download package source
        run: |
          cd openwrt
          make download -j8 || make download -j1 V=s

      - name: Build Firmware (Memory-Safe Mode)
        run: |
          cd openwrt
          
          echo "::group::Building toolchain"
          make tools/install -j${{ github.event.inputs.make_threads }} || { echo "Toolchain build failed"; exit 1; }
          make toolchain/install -j${{ github.event.inputs.make_threads }} || { echo "Toolchain install failed"; exit 1; }
          echo "::endgroup::"
          
          echo "::group::Building target"
          make target/compile -j${{ github.event.inputs.make_threads }} || make target/compile -j1 V=s
          if [ $? -ne 0 ]; then echo "Target compilation failed"; exit 1; fi
          echo "::endgroup::"
          
          echo "::group::Building packages"
          make package/compile -j${{ github.event.inputs.make_threads }} || make package/compile -j1 V=s
          if [ $? -ne 0 ]; then echo "Package compilation failed"; exit 1; fi
          echo "::endgroup::"
          
          echo "::group::Installing packages"
          make package/install -j${{ github.event.inputs.make_threads }} || make package/install -j1
          if [ $? -ne 0 ]; then echo "Package installation failed"; exit 1; fi
          echo "::endgroup::"
          
          echo "::group::Building firmware"
          make target/install -j${{ github.event.inputs.make_threads }} || make target/install -j1
          if [ $? -ne 0 ]; then echo "Firmware build failed"; exit 1; fi
          make package/index
          echo "::endgroup::"
          
          echo "=== Generated Firmware Files ==="
          ls -lh bin/targets/x86/64/

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware-x86_64
          path: openwrt/bin/targets/x86/64/openwrt-*.{img.gz,bin}

      - name: Upload Config
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-config-x86_64
          path: openwrt/.config
