name: Build OpenWrt 23.05.2 with Custom Packages

on:
  workflow_dispatch:
    inputs:
      target_device:
        description: 'Target device (e.g., x86_64, rpi-4)'
        required: true
        default: 'x86_64'
      make_threads:
        description: 'Threads for compilation (1-4, smaller is more stable)'
        required: true
        default: '2'

env:
  OPENWRT_VERSION: '23.05.2'
  REPO_URL: 'https://github.com/openwrt/openwrt'
  REPO_BRANCH: 'openwrt-23.05'
  ROOTFS_PARTSIZE: '2048'  # 减小固件分区大小以加快编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        run: |
          # 移除未使用的大型软件包和缓存
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache
          sudo apt-get clean
          # 移除 swap 分区以释放空间
          sudo swapoff -a
          sudo rm -f /swapfile
          # 显示可用空间
          df -h
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache curl file g++ gawk \
            git libncurses5-dev libssl-dev python3 unzip zlib1g-dev \
            subversion libxml-parser-perl default-jre-headless

      - name: Clone OpenWrt Source
        run: |
          git clone --depth 1 -b ${{ env.REPO_BRANCH }} ${{ env.REPO_URL }} openwrt
          cd openwrt
          
          # 启用并行下载以加速
          echo "CONFIG_DOWNLOAD_FOLDER=\"$(pwd)/dl\"" > .config
          echo "CONFIG_DEVEL=y" >> .config
          echo "CONFIG_ALL_NONSHARED=y" >> .config
          
          # 更新 feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure OpenWrt
        run: |
          cd openwrt
          
          # 克隆精简的必要软件包
          git clone https://github.com/vernesong/OpenClash.git package/openclash || echo "Failed to clone OpenClash"
          git clone https://github.com/xiaorouji/openwrt-passwall.git package/passwall || echo "Failed to clone PassWall"
          git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon || echo "Failed to clone Argon theme"

          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # 生成精简的配置
          cat << EOF > .config
          CONFIG_TARGET_${{ github.event.inputs.target_device }}=y
          CONFIG_TARGET_${{ github.event.inputs.target_device }}_Generic=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-opkg=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_kmod-r8169=y
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
          CONFIG_PACKAGE_openssh-sftp-server=y
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_LUCI_THEME_DEFAULT="argon"
          CONFIG_TARGET_ROOTFS_PARTSIZE=${{ env.ROOTFS_PARTSIZE }}
          CONFIG_TARGET_ROOTFS_EXT4FS=y
          CONFIG_TARGET_ROOTFS_SQUASHFS=y
          CONFIG_CCACHE=y
          # 禁用不需要的功能以加快编译
          CONFIG_KERNEL_KALLSYMS=n
          CONFIG_KERNEL_DEBUG_INFO=n
          CONFIG_KERNEL_DEBUG_KERNEL=n
          CONFIG_KERNEL_SWAP=n
          EOF
          
          # 应用配置并准备构建
          make defconfig
          
          # 显示配置摘要
          make -j1 V=s config-summary

      - name: Download package source
        run: |
          cd openwrt
          make download -j8
          # 检查下载是否有遗漏
          make download -j1 V=s

      - name: Build Firmware (Memory-Safe Mode)
        run: |
          cd openwrt
          
          # 分阶段编译以减少内存使用
          # 1. 先编译工具链
          make tools/install -j${{ github.event.inputs.make_threads }}
          make toolchain/install -j${{ github.event.inputs.make_threads }}
          
          # 2. 编译基本包
          make target/compile -j${{ github.event.inputs.make_threads }} || make target/compile -j1 V=s
          
          # 3. 编译软件包
          make package/compile -j${{ github.event.inputs.make_threads }} || make package/compile -j1 V=s
          
          # 4. 安装软件包
          make package/install -j${{ github.event.inputs.make_threads }} || make package/install -j1
          
          # 5. 生成固件
          make target/install -j${{ github.event.inputs.make_threads }} || make target/install -j1
          make package/index
          
          # 显示生成的固件文件
          echo "=== Generated Firmware Files ==="
          ls -lh bin/targets/*/*/

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware-${{ github.event.inputs.target_device }}
          path: openwrt/bin/targets/*/*/openwrt-*.*
          
      - name: Upload Config
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-config-${{ github.event.inputs.target_device }}
          path: openwrt/.config
