name: Build OpenWrt 23.05.2 with Custom Packages for x86_64

on:
  workflow_dispatch:
    inputs:
      make_threads:
        description: 'Threads for compilation (1-4, smaller is more stable)'
        required: true
        default: '2'

env:
  OPENWRT_VERSION: '23.05.2'
  REPO_URL: 'https://github.com/openwrt/openwrt'
  REPO_BRANCH: 'openwrt-23.05'
  ROOTFS_PARTSIZE: '2048'
  TARGET_DEVICE: 'x86_64'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache
          sudo apt-get clean
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache curl file g++ gawk \
            git libncurses5-dev libssl-dev python3 unzip zlib1g-dev \
            subversion libxml-parser-perl default-jre-headless

      - name: Clone OpenWrt Source
        run: |
          git clone --depth 1 -b ${{ env.REPO_BRANCH }} ${{ env.REPO_URL }} openwrt
          cd openwrt
          echo "CONFIG_DOWNLOAD_FOLDER=\"$(pwd)/dl\"" > .config
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure OpenWrt
        run: |
          cd openwrt
          
          # Clone OpenClash
          git clone https://github.com/vernesong/OpenClash.git package/openclash
          if [ $? -ne 0 ]; then echo "Failed to clone OpenClash"; exit 1; fi
          
          # Clone PassWall
          mkdir -p package/passwall
          git clone -b main https://github.com/xiaorouji/openwrt-passwall.git package/passwall/luci-app-passwall
          if [ $? -ne 0 ]; then echo "Failed to clone PassWall"; exit 1; fi
          
          # Clone Argon theme
          git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
          if [ $? -ne 0 ]; then echo "Failed to clone Argon theme"; exit 1; fi

          # Update feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # Generate configuration for x86_64
          cat << EOF > .config
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-opkg=y
          CONFIG_PACKAGE_luci-app-openclash=y
          
          # PassWall and dependencies
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_chinadns-ng=y
          CONFIG_PACKAGE_dns2socks=y
          CONFIG_PACKAGE_tcping=y
          CONFIG_PACKAGE_v2ray-core=y
          CONFIG_PACKAGE_xray-core=y
          CONFIG_PACKAGE_brook=y
          CONFIG_PACKAGE_trojan-plus=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          
          # Network drivers
          CONFIG_PACKAGE_kmod-r8169=y
          CONFIG
